from abc import ABC

from .entities import Member, Team


class MemberRepository(ABC):
    def create(self, name: str, position: str) -> Member: ...
    def get_by_id(self, id) -> Member: ...
    def remove(self, id) -> None: ...


class TeamRepository(ABC):
    def create(self, name: str) -> Team: ...
    def get_by_id(self, id) -> Team: ...
    def add_member(self, id, member_id) -> None: ...
    def add_members(self, id, member_ids: list) -> None: ...
    def remove_member(self, id, member_id) -> None: ...
    def remove_members(self, id, member_ids: list) -> None: ...
    def remove(self, id) -> None: ...
