from abc import ABC

from .entities import Member, Team


class MemberRepository(ABC):
    def get_list(self) -> list[Member]: ...
    def create(self, name: str, position: str, team_id) -> Member: ...
    def update(self, id, **kwargs) -> bool: ...
    def get_by_id(self, id) -> Member: ...
    def set_team_id(self, id, team_id) -> None: ...
    def remove(self, id) -> None: ...


class TeamRepository(ABC):
    def get_list(self) -> list[Team]: ...
    def create(self, name: str) -> Team: ...
    def update(self, id, **kwargs) -> bool: ...
    def get_by_id(self, id) -> Team: ...
    def remove(self, id) -> None: ...
