# Generated by Django 5.0.7 on 2024-08-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0003_remove_member_user_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
